- name: Deploy Maven Artifact
  hosts: localhost
  become: false
  tasks:
    - name: Create deployment directory if it does not exist
      file:
        path: /home/jenkins/deployment
        state: directory
        mode: '0755'

    - name: Copy the artifact to the deployment directory
      copy:
        src: "/var/lib/jenkins/workspace/myapp/target/myapp-1.0-SNAPSHOT.jar"
        dest: "/opt/deployment/myapp.jar"
